/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.neuromancer42.tea.souffle.swig;

public class SwigInterface {
  public static SWIGSouffleProgram newInstance(String name) {
    long cPtr = SwigInterfaceJNI.newInstance(name);
    return (cPtr == 0) ? null : new SWIGSouffleProgram(cPtr, false);
  }

}
