# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from application import core_util_pb2 as application_dot_core__util__pb2


class CoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAnalyses = channel.unary_stream(
                '/tea.core.CoreService/RunAnalyses',
                request_serializer=application_dot_core__util__pb2.ApplicationRequest.SerializeToString,
                response_deserializer=application_dot_core__util__pb2.ApplicationResponse.FromString,
                )


class CoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunAnalyses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAnalyses': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAnalyses,
                    request_deserializer=application_dot_core__util__pb2.ApplicationRequest.FromString,
                    response_serializer=application_dot_core__util__pb2.ApplicationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tea.core.CoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAnalyses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tea.core.CoreService/RunAnalyses',
            application_dot_core__util__pb2.ApplicationRequest.SerializeToString,
            application_dot_core__util__pb2.ApplicationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
